"""
Generates src/data/legal-privacy.ts from the privacy policy published on
mengoengine.com, so the client's own legal wording is preserved rather than
paraphrased. Re-run only when the source policy changes.

Usage: python scripts/gen-privacy.py <privacy.json>
"""
import io
import json
import sys

BACKSLASH = chr(92)
QUOTE = '"'


def q(text):
    escaped = text.replace(BACKSLASH, BACKSLASH * 2).replace(QUOTE, BACKSLASH + QUOTE)
    return QUOTE + escaped + QUOTE


def main(path):
    sections = json.load(io.open(path, encoding="utf-8"))
    out = [
        'import type { Section } from "@/lib/types";',
        "",
        "/**",
        " * Privacy policy, reproduced from the policy published on mengoengine.com.",
        " *",
        " * This is the client's own legal text, preserved rather than rewritten.",
        " * Last Updated on the source page: 08/07/2026. Amendments should be made",
        " * against the authoritative copy Mengo's legal adviser holds, not here.",
        " *",
        " * Generated by scripts/gen-privacy.py.",
        " */",
        "export const privacySections: Section[] = [",
    ]
    for section in sections:
        out.append("  {")
        out.append("    heading: " + q(section["heading"]) + ",")
        out.append("    blocks: [")
        for kind, value in section["blocks"]:
            if kind == "text":
                out.append('      { type: "text", text: ' + q(value) + " },")
            else:
                items = ", ".join(q(v) for v in value)
                out.append('      { type: "list", items: [' + items + "] },")
        out.append("    ],")
        out.append("  },")
    out.append("];")
    io.open("src/data/legal-privacy.ts", "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("wrote " + str(len(sections)) + " sections")


if __name__ == "__main__":
    main(sys.argv[1])
