import type { Section } from "@/lib/types";

/**
 * Privacy policy, reproduced from the policy published on mengoengine.com.
 *
 * This is the client's own legal text, preserved rather than rewritten.
 * Last Updated on the source page: 08/07/2026. Amendments should be made
 * against the authoritative copy Mengo's legal adviser holds, not here.
 *
 * Generated by scripts/gen-privacy.py.
 */
export const privacySections: Section[] = [
  {
    heading: "1. Information We Collect",
    blocks: [
      { type: "text", text: "We collect information to provide, improve, secure, and personalize our Services." },
      { type: "text", text: "Information You Provide Directly" },
      { type: "text", text: "This may include:" },
      { type: "list", items: ["Name", "Email address", "Phone number", "Company name", "Business details", "Marketing goals", "Billing information", "Account credentials", "Support communications", "Survey responses", "Waitlist submissions"] },
      { type: "text", text: "Business and Marketing Inputs" },
      { type: "text", text: "To generate outputs and recommendations, Mengo may collect:" },
      { type: "list", items: ["Business descriptions", "Audience information", "Brand positioning", "Marketing objectives", "Content preferences", "Campaign details", "Platform selections", "Workflow instructions"] },
      { type: "text", text: "Automatically Collected Information" },
      { type: "text", text: "When you interact with our Services, we may automatically collect:" },
      { type: "list", items: ["IP address", "Browser type", "Device information", "Operating system", "Location information (approximate)", "Referral URLs", "Usage data", "Session information", "Cookies and tracking data"] },
      { type: "text", text: "Generated Data" },
      { type: "text", text: "We may create derived information including:" },
      { type: "list", items: ["AI generated content", "Marketing workflows", "Lead nurturing structures", "Usage analytics", "Performance insights", "Platform recommendations"] },
    ],
  },
  {
    heading: "2. How We Use Your Information",
    blocks: [
      { type: "text", text: "We use collected information to:" },
      { type: "list", items: ["Provide and operate Mengo", "Generate marketing systems and outputs", "Improve platform performance", "Personalize user experience", "Process registrations and payments", "Respond to support requests", "Analyze platform usage", "Detect fraud and misuse", "Maintain security", "Develop new features", "Send product communications", "Comply with legal obligations"] },
    ],
  },
  {
    heading: "3. AI Processing and Generated Outputs",
    blocks: [
      { type: "text", text: "Mengo uses automated systems and AI technologies to process information you provide." },
      { type: "text", text: "By using Mengo:" },
      { type: "list", items: ["You authorize us to process submitted inputs to generate outputs.", "Outputs may vary based on provided information and system improvements.", "Generated outputs should be reviewed before publication or execution.", "Users remain responsible for decisions, publishing activities, and implementation.", "Mengo does not guarantee business outcomes, conversion rates, or marketing performance."] },
    ],
  },
  {
    heading: "4. Ownership of Data and Intellectual Property",
    blocks: [
      { type: "text", text: "Your Inputs" },
      { type: "text", text: "You retain ownership of business information, materials, and content submitted to Mengo." },
      { type: "text", text: "Generated Outputs" },
      { type: "text", text: "Unless otherwise stated in a separate agreement:" },
      { type: "list", items: ["Outputs generated specifically for your account belong to you.", "Mengo retains ownership of underlying software, models, systems, templates, algorithms, workflows, and platform infrastructure."] },
      { type: "text", text: "Platform Rights" },
      { type: "text", text: "You may not:" },
      { type: "list", items: ["Reverse engineer the platform", "Replicate Mengo's architecture", "Extract proprietary workflows", "Train competing systems using Mengo outputs", "Copy platform functionality for commercial redistribution"] },
    ],
  },
  {
    heading: "5. Cookies and Tracking Technologies",
    blocks: [
      { type: "text", text: "Mengo uses cookies and similar technologies to improve performance and user experience." },
      { type: "text", text: "Cookies may be used for:" },
      { type: "list", items: ["Authentication", "Preferences", "Security", "Analytics", "Performance measurement", "Session continuity", "Marketing effectiveness"] },
      { type: "text", text: "Types of cookies may include:" },
      { type: "text", text: "Essential Cookies" },
      { type: "text", text: "Required for platform functionality." },
      { type: "text", text: "Analytics Cookies" },
      { type: "text", text: "Help us understand usage patterns." },
      { type: "text", text: "Functional Cookies" },
      { type: "text", text: "Store preferences and improve experience." },
      { type: "text", text: "Marketing Cookies" },
      { type: "text", text: "Support communication and campaign measurement." },
      { type: "text", text: "You may manage cookies through browser settings. Disabling cookies may limit some functionality." },
    ],
  },
  {
    heading: "6. Data Sharing and Third Parties",
    blocks: [
      { type: "text", text: "We do not sell personal information. We may share information with:" },
      { type: "list", items: ["Infrastructure providers", "Analytics providers", "Payment processors", "Communication tools", "Customer support services", "Legal and regulatory authorities", "Business partners supporting service delivery"] },
      { type: "text", text: "Third parties are expected to process information according to applicable privacy obligations." },
    ],
  },
  {
    heading: "7. Data Retention",
    blocks: [
      { type: "text", text: "We retain information only for as long as necessary to:" },
      { type: "list", items: ["Provide Services", "Maintain accounts", "Meet legal obligations", "Resolve disputes", "Improve products", "Enforce agreements"] },
      { type: "text", text: "Retention periods may vary depending on account activity and regulatory requirements." },
    ],
  },
  {
    heading: "8. Security Measures",
    blocks: [
      { type: "text", text: "We implement commercially reasonable safeguards including:" },
      { type: "list", items: ["Encryption practices", "Access controls", "Authentication mechanisms", "Monitoring systems", "Infrastructure protections", "Security review processes"] },
      { type: "text", text: "No method of transmission or storage can be guaranteed to be completely secure." },
    ],
  },
  {
    heading: "9. International Data Transfers",
    blocks: [
      { type: "text", text: "Your information may be processed and stored in jurisdictions outside your country of residence. Where required, Mengo uses reasonable safeguards for cross border data transfers." },
    ],
  },
  {
    heading: "10. Your Privacy Rights",
    blocks: [
      { type: "text", text: "Depending on your location, you may have rights to:" },
      { type: "list", items: ["Access your information", "Correct inaccurate data", "Request deletion", "Restrict processing", "Withdraw consent", "Export your information", "Object to certain processing"] },
      { type: "text", text: "Requests may be submitted using the contact details below." },
    ],
  },
  {
    heading: "11. Account and Data Deletion",
    blocks: [
      { type: "text", text: "You may request deletion of your account and associated personal information. Certain information may be retained where legally required or necessary for operational, fraud prevention, or compliance purposes." },
    ],
  },
  {
    heading: "12. Children's Privacy",
    blocks: [
      { type: "text", text: "Mengo is not directed toward children under the age required by applicable law. We do not knowingly collect information from children." },
    ],
  },
  {
    heading: "13. Communications",
    blocks: [
      { type: "text", text: "We may send:" },
      { type: "list", items: ["Account updates", "Product announcements", "Security notices", "Service communications", "Optional marketing messages"] },
      { type: "text", text: "You may unsubscribe from marketing communications at any time." },
    ],
  },
  {
    heading: "14. User Responsibilities",
    blocks: [
      { type: "text", text: "You agree not to submit:" },
      { type: "list", items: ["Illegal content", "Infringing materials", "Harmful code", "Sensitive personal information without authorization", "Content you do not have rights to use"] },
      { type: "text", text: "You remain responsible for all information submitted through your account." },
    ],
  },
  {
    heading: "15. Changes to This Privacy Policy",
    blocks: [
      { type: "text", text: "We may update this Privacy Policy periodically. Material updates will become effective upon publication unless otherwise required by law." },
    ],
  },
  {
    heading: "16. Contact Us",
    blocks: [
      { type: "text", text: "If you have questions about this Privacy Policy or privacy practices, contact:" },
    ],
  },
];
